### ISSUE TITLE
Improper data on Trip Confirmation page

### ISSUE THREAD

**Issue by prasadc82** [lokeshjain2008/spareSeat#10]
**Android**
**Context**  Passenger has a Trip
**Description** Passenger selects a driver trip, On Trip Confirmation page the details displayed is wrong

**Comment by lokeshjain2008** [comment]
This is due to the permission issues. Let's work on the database structure. I request you to book a time for this.

**Comment by lokeshjain2008** [comment]
To write better permission files. There a tool [bolt](https://github.com/firebase/bolt)

**Comment by prasadc82** [comment]
Ok. Got the issue.

So when the passenger selects driver trip and confirms ( thru trip confirmation page ), currently trying to make both the trips ( Driver and Passenger ) as 'Pending'. Passenger was not having write permissions on passenger trip Firebase node hence error was thrown and the while data saved was incorrect.

Temporary Fix; Now the passenger can write on Driver trip node
Longer term; Need to restructure the DB nodes.
