### ISSUE TITLE
Login does not work on Android

### ISSUE THREAD

**Issue by prasadc82** [lokeshjain2008/spareSeat#8]
**Android**
**context:** User have installed FB APP in the device and already logged into FB using FB App
**Description:** User will not be able to Login to SpareSeat

**Comment by lokeshjain2008** [comment]
I have found the reason that was causing this issue. please refer to the email.

**Comment by prasadc82** [comment]
ok. Got the Hash Key by;
keytool -exportcert -alias androiddebugkey -keystore ~/.android/debug.keystore | openssl sha1 -binary | openssl base64

and added the Hash key to FB App.

**This only works for debug builds ( builds pushed through USB ).**

For Release builds we may need to follow;
- http://ionicframework.com/docs/intro/deploying/
